name: Flux Push OCI Release

on:
  push:
    branches:
      - 'main'
    tags:
      - 'release/*'

jobs:
  flux:
    env:
      IMAGE: ghcr.io/kingdonb/river-data-explorer-config
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: '^1.17.0'

      - name: Prepare
        id: prep
        run: |
          GIT_TAG=${GITHUB_REF/refs\/tags\/release\//}
          FLUX_PATH=${GITHUB_WORKSPACE}/bin
          FLUX_OCI_SHA=0c89b8d4be118a86e2aea157a64fcd2479746e69
          mkdir flux2 && pushd flux2
          git init
          git remote add origin https://github.com/fluxcd/flux2
          # git clone --depth 1 https://github.com/fluxcd/flux2 -b oci
          git fetch --depth 1 origin $FLUX_OCI_SHA
          git checkout FETCH_HEAD
          # pushd flux2
          FLUX_OCI_SHA=$(git rev-parse --short HEAD)
          popd
          mkdir -p "${FLUX_PATH}"
          echo "${FLUX_PATH}" >> $GITHUB_PATH
      
          echo ::set-output name=GIT_TAG::${GIT_TAG}
          echo ::set-output name=FLUX_PATH::${FLUX_PATH}
          echo ::set-output name=FLUX_OCI_SHA::${FLUX_OCI_SHA}

      - id: go-cache-paths
        run: |
          echo "::set-output name=go-build::$(go env GOCACHE)"
          echo "::set-output name=go-mod::$(go env GOMODCACHE)"

      - name: Cache Flux OCI (prerelease)
        id: cache-flux
        uses: actions/cache@v3
        env:
          cache-name: flux
        with:
          path: ${{ steps.prep.outputs.FLUX_PATH }}
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ steps.prep.outputs.FLUX_OCI_SHA }}

      - name: Go Build Cache
        if: steps.cache-flux.outputs.cache-hit != 'true'
        uses: actions/cache@v2
        with:
          path: ${{ steps.go-cache-paths.outputs.go-build }}
          key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}

      - name: Go Mod Cache
        if: steps.cache-flux.outputs.cache-hit != 'true'
        uses: actions/cache@v2
        with:
          path: ${{ steps.go-cache-paths.outputs.go-mod }}
          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}

      - name: Build Flux (pre-release)
        if: steps.cache-flux.outputs.cache-hit != 'true'
        id: build-flux-oci
        run: |
          pushd flux2
          make build
          cp bin/flux ${{ steps.prep.outputs.FLUX_PATH }}
          popd

      - name: Login to GHCR
        uses: docker/login-action@v1
        if: github.event_name == 'push' && github.ref_type == 'tag'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Flux push OCI Repository
        id: oci_push
        if: github.event_name == 'push' && github.ref_type == 'tag'
        run: |
          flux push artifact ${{ env.IMAGE }}:${{ steps.prep.outputs.GIT_TAG }} \
            --path="./deploy" \
            --source="$(git config --get remote.origin.url)" \
            --revision="$(git branch --show-current)/$(git rev-parse HEAD)"
